// <auto-generated />
using System;
using Chapter12;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chapter12.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20211013115119_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Chapter12.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Chapter12.Good", b =>
                {
                    b.Property<int>("GoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Unit_Price")
                        .HasColumnType("double");

                    b.HasKey("GoodId");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("Chapter12.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Customer_CustomerId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("Customer_CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Chapter12.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Goods_Num")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("good_GoodId")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("good_GoodId");

                    b.ToTable("orderDetails");
                });

            modelBuilder.Entity("Chapter12.Order", b =>
                {
                    b.HasOne("Chapter12.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Chapter12.OrderDetail", b =>
                {
                    b.HasOne("Chapter12.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chapter12.Good", "good")
                        .WithMany()
                        .HasForeignKey("good_GoodId");

                    b.Navigation("good");

                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
